import { useState, useRef, useEffect } from 'react'
import { 
  Server, Thermometer, Wind, Monitor, Lightbulb, Users, 
  Blinds, Wifi, Coffee, Bell, CheckCircle2, AlertTriangle, 
  XCircle, MessageSquare, Send, Bot, X, ChevronRight, Activity, Zap, Clock
} from 'lucide-react'

function Insights() {
  const [chatOpen, setChatOpen] = useState(false)
  const [chatInput, setChatInput] = useState('')
  const [messages, setMessages] = useState([
    { role: 'ai', content: 'Hello! I am your SmartSense AI Copilot. I can analyze the current room insights for you. For example, you can ask "Why is the Server Room critical?"' }
  ])
  const messagesEndRef = useRef(null)

  const [selectedRoom, setSelectedRoom] = useState(null)
  const [selectedDevice, setSelectedDevice] = useState(null)

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }

  useEffect(() => {
    scrollToBottom()
  }, [messages, chatOpen])

  const handleSendMessage = (e) => {
    e.preventDefault()
    if (!chatInput.trim()) return

    const userMessage = chatInput.trim()
    setMessages(prev => [...prev, { role: 'user', content: userMessage }])
    setChatInput('')

    setTimeout(() => {
      let aiResponse = "Analyzing telemetry data..."
      const lowerInput = userMessage.toLowerCase()
      if (lowerInput.includes('server')) {
        aiResponse = "The Server Room is CRITICAL. The Temperature Sensor is reading 28°C (exceeding 24°C threshold). The HVAC Unit is drawing 4.2kW (Warning), indicating potential failure. Immediate maintenance is recommended."
      } else if (lowerInput.includes('office') || lowerInput.includes('filter')) {
        aiResponse = "Executive Office is in WARNING state. The Air Purifier HEPA filter is at 90% capacity and requires replacement. Other devices are optimal."
      } else {
        aiResponse = "Overall facility health is 80%. 1 Critical issue (Server Room) and 1 Warning (Executive Office) detected. Would you like to create a maintenance ticket?"
      }
      setMessages(prev => [...prev, { role: 'ai', content: aiResponse }])
    }, 1000)
  }

  const rooms = [
    {
      id: 1,
      name: 'Server Room Alpha',
      status: 'critical',
      details: {
        powerUsage: '14.2 kW',
        avgTemp: '26.5°C',
        occupancy: '0 (Restricted)',
        lastMaintenance: '14 days ago',
        aiInsight: 'Critical thermal event detected. Cooling systems are failing to offset the heat generated by Rack Servers. Immediate load balancing or supplementary cooling required to prevent hardware damage.'
      },
      devices: [
        { id: 'd1', name: 'HVAC Unit A', status: 'warning', metric: 'High power draw (4.2kW)', icon: Wind, details: { model: 'AeroCool Pro X', firmware: 'v2.1', uptime: '45 days', draw: '18.5 A', aiInsight: 'Compressor cycle times increased by 40%. Probable refrigerant leak or blocked intake.', aiSolution: '1. Inspect and clean external air intakes. 2. Dispatch a technician to verify R-410A refrigerant levels.' } },
        { id: 'd2', name: 'Temp Sensor', status: 'critical', metric: 'Reading 28°C (Threshold: 24°C)', icon: Thermometer, details: { model: 'ThermoSense 500', firmware: 'v1.4', uptime: '120 days', draw: '0.1 A', aiInsight: 'Sensor reading confirmed by adjacent nodes. Thermal gradient indicates heat source is concentrated near Server Rack 2.', aiSolution: '1. Immediately power down non-essential workloads on Rack 2. 2. Enable auxiliary cooling fans.' } },
        { id: 'd3', name: 'Rack Servers', status: 'optimal', metric: 'Uptime 99.9%', icon: Server, details: { model: 'Dell PowerEdge Gen15', firmware: 'v4.0', uptime: '365 days', draw: '45.0 A', aiInsight: 'CPU temperatures are approaching thermal throttling limits (85°C). Performance degradation imminent if ambient temp is not reduced.' } },
      ]
    },
    {
      id: 2,
      name: 'Executive Office Suite',
      status: 'warning',
      details: {
        powerUsage: '1.2 kW',
        avgTemp: '22.0°C',
        occupancy: '1',
        lastMaintenance: '60 days ago',
        aiInsight: 'Overall environment is stable, but air quality metrics are slowly declining. Scheduling filter replacement during off-hours is advised.'
      },
      devices: [
        { id: 'd4', name: 'Air Purifier', status: 'warning', metric: 'Filter replacement due', icon: Wind, details: { model: 'PureAir Elite', firmware: 'v1.1', uptime: '90 days', draw: '2.5 A', aiInsight: 'HEPA filter capacity at 92%. Particulate matter (PM2.5) levels in the room have increased by 15% over the last week.', aiSolution: 'Order replacement HEPA filter (Part #HEPA-900) and schedule maintenance window during off-hours to swap the filter.' } },
        { id: 'd5', name: 'Smart Blinds', status: 'optimal', metric: 'Auto-adjust active', icon: Blinds, details: { model: 'Somfy Glydea', firmware: 'v3.2', uptime: '210 days', draw: '0.5 A', aiInsight: 'Operating nominally. Automatically adjusting to minimize solar heat gain during peak afternoon hours.' } },
        { id: 'd6', name: 'Smart Lighting', status: 'optimal', metric: 'Energy save mode', icon: Lightbulb, details: { model: 'Philips Hue Pro', firmware: 'v2.8', uptime: '300 days', draw: '1.2 A', aiInsight: 'Daylight harvesting is active. Current artificial lighting is dimmed to 40%, saving approximately 0.5 kWh daily.' } },
      ]
    },
    {
      id: 3,
      name: 'Main Conference Room',
      status: 'optimal',
      details: {
        powerUsage: '0.5 kW',
        avgTemp: '21.5°C',
        occupancy: '0',
        lastMaintenance: '30 days ago',
        aiInsight: 'Room is currently vacant. All systems have successfully entered deep sleep energy-saving modes.'
      },
      devices: [
        { id: 'd7', name: 'Smart Board', status: 'optimal', metric: 'Standby mode', icon: Monitor, details: { model: 'Samsung Flip 3', firmware: 'v5.1', uptime: '15 days', draw: '0.2 A', aiInsight: 'Entered standby mode 45 minutes ago following the last scheduled meeting. Ready for quick wake.' } },
        { id: 'd8', name: 'Occupancy Sensor', status: 'optimal', metric: 'Room Empty', icon: Users, details: { model: 'SenseMotion X', firmware: 'v1.0', uptime: '400 days', draw: '0.05 A', aiInsight: 'No motion detected for 45 minutes. Accuracy confidence: 99.8%.' } },
        { id: 'd9', name: 'Lighting Control', status: 'optimal', metric: 'Lights OFF', icon: Lightbulb, details: { model: 'Lutron Quantum', firmware: 'v4.4', uptime: '150 days', draw: '0.1 A', aiInsight: 'Lighting schedule is synced with calendar events. Next automated power-on scheduled for 2:00 PM.' } },
      ]
    },
    {
      id: 4,
      name: 'Open Workspace A',
      status: 'optimal',
      details: {
        powerUsage: '8.4 kW',
        avgTemp: '22.5°C',
        occupancy: '45',
        lastMaintenance: '45 days ago',
        aiInsight: 'High occupancy detected. HVAC and ventilation systems have automatically scaled up to maintain air quality and temperature setpoints.'
      },
      devices: [
        { id: 'd10', name: 'Zone HVAC', status: 'optimal', metric: 'Stable at 22°C', icon: Wind, details: { model: 'Trane IntelliPak', firmware: 'v6.0', uptime: '120 days', draw: '25.0 A', aiInsight: 'Running at 60% capacity to manage human heat load. VAV boxes are dynamically adjusting airflow to perimeter zones.' } },
        { id: 'd11', name: 'WiFi Access Point', status: 'optimal', metric: 'Speed: 1.2 Gbps', icon: Wifi, details: { model: 'Cisco Meraki MR56', firmware: 'v28.5', uptime: '60 days', draw: '1.5 A', aiInsight: 'Handling 124 concurrent client connections. Spectrum analysis shows low interference on 5GHz bands.' } },
        { id: 'd12', name: 'Ambient Light', status: 'optimal', metric: 'Auto-dimming active', icon: Lightbulb, details: { model: 'Osram Encelium', firmware: 'v3.1', uptime: '180 days', draw: '4.0 A', aiInsight: 'Lux sensors report adequate natural light near windows. Perimeter fixtures are dimmed to 20%.' } },
      ]
    },
    {
      id: 5,
      name: 'Cafeteria & Lounge',
      status: 'optimal',
      details: {
        powerUsage: '5.6 kW',
        avgTemp: '23.0°C',
        occupancy: '12',
        lastMaintenance: '10 days ago',
        aiInsight: 'Off-peak hours. Appliances are operating within normal parameters. Vending machine inventory is sufficient for the remainder of the week.'
      },
      devices: [
        { id: 'd13', name: 'Smart Vending', status: 'optimal', metric: 'Inventory OK', icon: Coffee, details: { model: 'VendSense Pro', firmware: 'v1.9', uptime: '30 days', draw: '3.5 A', aiInsight: 'Beverage stock is at 65%. Snack stock is at 80%. Compressor cycling normally.' } },
        { id: 'd14', name: 'HVAC Unit', status: 'optimal', metric: 'Stable at 23°C', icon: Wind, details: { model: 'Carrier Infinity', firmware: 'v4.2', uptime: '90 days', draw: '12.0 A', aiInsight: 'Operating in eco-mode. Make-up air unit is providing sufficient ventilation for current occupancy.' } },
        { id: 'd15', name: 'Smoke Detector', status: 'optimal', metric: 'All clear', icon: Bell, details: { model: 'Nest Protect Pro', firmware: 'v2.0', uptime: '500 days', draw: '0.1 A', aiInsight: 'Self-test completed successfully at 3:00 AM. Battery backup is at 100% capacity.' } },
      ]
    }
  ]

  const getStatusConfig = (status) => {
    switch(status) {
      case 'critical': return { bg: 'bg-red-50', border: 'border-red-200', text: 'text-red-700', badge: 'bg-red-100 text-red-800', icon: XCircle, iconColor: 'text-red-500' }
      case 'warning': return { bg: 'bg-amber-50', border: 'border-amber-200', text: 'text-amber-700', badge: 'bg-amber-100 text-amber-800', icon: AlertTriangle, iconColor: 'text-amber-500' }
      case 'optimal': return { bg: 'bg-green-50', border: 'border-green-200', text: 'text-green-700', badge: 'bg-green-100 text-green-800', icon: CheckCircle2, iconColor: 'text-green-500' }
      default: return { bg: 'bg-gray-50', border: 'border-gray-200', text: 'text-gray-700', badge: 'bg-gray-100 text-gray-800', icon: CheckCircle2, iconColor: 'text-gray-500' }
    }
  }

  // Handle outside click for modals
  const closeModal = (e) => {
    if (e.target.id === 'modal-overlay') {
      setSelectedRoom(null)
      setSelectedDevice(null)
    }
  }

  return (
    <div className="max-w-7xl mx-auto pb-10 relative">
      <div className="mb-8">
        <h2 className="text-3xl font-extrabold text-gray-900">Facility Monitoring Insights</h2>
        <p className="text-gray-500 mt-1">Real-time telemetry and device health across all facility rooms.</p>
      </div>

      <div className="grid lg:grid-cols-2 xl:grid-cols-3 gap-6">
        {rooms.map((room) => {
          const roomStatus = getStatusConfig(room.status)
          const StatusIcon = roomStatus.icon
          
          return (
            <div key={room.id} className={`bg-white rounded-2xl card-shadow border ${roomStatus.border} overflow-hidden flex flex-col transition-transform hover:-translate-y-1 hover:shadow-lg duration-300`}>
              {/* Room Header */}
              <div className={`px-5 py-4 border-b ${roomStatus.border} ${roomStatus.bg} flex justify-between items-center`}>
                <h3 className={`font-bold text-lg ${roomStatus.text}`}>{room.name}</h3>
                <StatusIcon className={`w-6 h-6 ${roomStatus.iconColor}`} />
              </div>
              
              {/* Device List */}
              <div className="p-5 flex-1 flex flex-col gap-3">
                {room.devices.map((device) => {
                  const devStatus = getStatusConfig(device.status)
                  const DevStatusIcon = devStatus.icon
                  const DeviceIcon = device.icon

                  return (
                    <div 
                      key={device.id} 
                      onClick={() => setSelectedDevice({ roomName: room.name, ...device })}
                      className={`flex items-start gap-3 p-2 rounded-xl cursor-pointer transition-colors hover:bg-gray-50 border border-transparent hover:border-gray-200`}
                    >
                      <div className={`p-2 rounded-lg ${devStatus.bg} ${devStatus.text}`}>
                        <DeviceIcon className="w-5 h-5" />
                      </div>
                      <div className="flex-1">
                        <div className="flex justify-between items-center">
                          <span className="font-bold text-gray-800 text-sm group-hover:text-red-600 transition-colors">{device.name}</span>
                          <DevStatusIcon className={`w-4 h-4 ${devStatus.iconColor}`} />
                        </div>
                        <p className={`text-xs mt-0.5 ${device.status === 'optimal' ? 'text-gray-500' : devStatus.text + ' font-medium'}`}>
                          {device.metric}
                        </p>
                      </div>
                    </div>
                  )
                })}
              </div>
              
              {/* Card Footer */}
              <div className="px-5 py-3 border-t border-gray-100 bg-gray-50 flex justify-between items-center mt-auto">
                <span className="text-xs text-gray-500 font-medium">Last updated: Just now</span>
                <button 
                  onClick={() => setSelectedRoom(room)}
                  className="text-red-600 text-sm font-semibold hover:underline flex items-center gap-1 px-3 py-1.5 rounded-lg hover:bg-red-50 transition-colors"
                >
                  Room Details <ChevronRight className="w-4 h-4" />
                </button>
              </div>
            </div>
          )
        })}
      </div>

      {/* Floating Chat Button */}
      <button 
        onClick={() => setChatOpen(true)}
        className="fixed bottom-8 right-8 bg-red-600 text-white p-4 rounded-full shadow-2xl hover:bg-red-700 transition-transform transform hover:scale-105 z-40 group"
      >
        <MessageSquare className="w-6 h-6" />
        <span className="absolute -top-1 -right-1 bg-white text-red-600 text-[10px] font-bold w-5 h-5 rounded-full flex items-center justify-center shadow-sm">1</span>
        <div className="absolute right-full mr-4 top-1/2 -translate-y-1/2 bg-gray-900 text-white text-sm font-medium px-3 py-1.5 rounded-lg opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap pointer-events-none">
          Ask AI Copilot
        </div>
      </button>

      {/* Chatbot Window */}
      {chatOpen && (
        <div className="fixed bottom-8 right-8 w-96 bg-white rounded-2xl shadow-2xl border border-gray-200 flex flex-col overflow-hidden z-50 animate-in slide-in-from-bottom-5">
          <div className="bg-gradient-to-r from-red-600 to-red-800 p-4 flex justify-between items-center text-white">
            <div className="flex items-center gap-2">
              <Bot className="w-6 h-6" />
              <span className="font-bold text-lg">SmartSense AI Copilot</span>
            </div>
            <button onClick={() => setChatOpen(false)} className="text-red-100 hover:text-white transition-colors">
              <X className="w-5 h-5" />
            </button>
          </div>
          
          <div className="h-96 overflow-y-auto p-4 bg-gray-50 flex flex-col gap-4">
            {messages.map((msg, idx) => (
              <div key={idx} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                <div className={`max-w-[80%] rounded-2xl px-4 py-2.5 text-sm ${
                  msg.role === 'user' 
                    ? 'bg-red-600 text-white rounded-br-sm shadow-sm' 
                    : 'bg-white text-gray-800 border border-gray-100 rounded-bl-sm shadow-sm'
                }`}>
                  {msg.content}
                </div>
              </div>
            ))}
            <div ref={messagesEndRef} />
          </div>
          
          <form onSubmit={handleSendMessage} className="p-3 bg-white border-t border-gray-100 flex gap-2">
            <input 
              type="text" 
              value={chatInput}
              onChange={(e) => setChatInput(e.target.value)}
              placeholder="Ask about device health..." 
              className="flex-1 bg-gray-100 border-transparent focus:bg-white focus:border-red-500 focus:ring-2 focus:ring-red-200 rounded-xl px-4 py-2 text-sm transition-colors"
            />
            <button 
              type="submit" 
              disabled={!chatInput.trim()}
              className="bg-red-600 text-white p-2 rounded-xl hover:bg-red-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <Send className="w-5 h-5" />
            </button>
          </form>
        </div>
      )}

      {/* Room Details Modal */}
      {selectedRoom && (
        <div id="modal-overlay" onClick={closeModal} className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4 animate-in fade-in">
          <div className="bg-white rounded-3xl w-full max-w-2xl overflow-hidden shadow-2xl animate-in zoom-in-95">
            {/* Modal Header */}
            <div className={`p-6 border-b ${getStatusConfig(selectedRoom.status).border} ${getStatusConfig(selectedRoom.status).bg} flex justify-between items-start`}>
              <div>
                <div className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-bold mb-2 ${getStatusConfig(selectedRoom.status).badge}`}>
                  {(() => {
                    const StatusIcon = getStatusConfig(selectedRoom.status).icon;
                    return <StatusIcon className="w-3.5 h-3.5" />
                  })()}
                  {selectedRoom.status.toUpperCase()}
                </div>
                <h2 className="text-2xl font-extrabold text-gray-900">{selectedRoom.name}</h2>
                <p className="text-gray-600 mt-1">Detailed Room Telemetry</p>
              </div>
              <button onClick={() => setSelectedRoom(null)} className="p-2 bg-white/50 rounded-full hover:bg-white transition-colors text-gray-500">
                <X className="w-6 h-6" />
              </button>
            </div>
            
            <div className="p-6">
              {/* Aggregate Stats */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
                <div className="bg-gray-50 p-4 rounded-2xl border border-gray-100">
                  <Activity className="w-5 h-5 text-blue-500 mb-2" />
                  <p className="text-xs text-gray-500 font-medium">Power Usage</p>
                  <p className="text-lg font-bold text-gray-900">{selectedRoom.details.powerUsage}</p>
                </div>
                <div className="bg-gray-50 p-4 rounded-2xl border border-gray-100">
                  <Thermometer className="w-5 h-5 text-red-500 mb-2" />
                  <p className="text-xs text-gray-500 font-medium">Avg Temp</p>
                  <p className="text-lg font-bold text-gray-900">{selectedRoom.details.avgTemp}</p>
                </div>
                <div className="bg-gray-50 p-4 rounded-2xl border border-gray-100">
                  <Users className="w-5 h-5 text-indigo-500 mb-2" />
                  <p className="text-xs text-gray-500 font-medium">Occupancy</p>
                  <p className="text-lg font-bold text-gray-900">{selectedRoom.details.occupancy}</p>
                </div>
                <div className="bg-gray-50 p-4 rounded-2xl border border-gray-100">
                  <Clock className="w-5 h-5 text-green-500 mb-2" />
                  <p className="text-xs text-gray-500 font-medium">Maintenance</p>
                  <p className="text-lg font-bold text-gray-900">{selectedRoom.details.lastMaintenance}</p>
                </div>
              </div>

              {/* AI Insight */}
              <div className="bg-blue-50 border border-blue-100 rounded-2xl p-5 mb-6">
                <div className="flex items-center gap-2 mb-2">
                  <Bot className="w-5 h-5 text-blue-600" />
                  <h4 className="font-bold text-blue-900">SmartSense AI Analysis</h4>
                </div>
                <p className="text-blue-800 text-sm leading-relaxed">
                  {selectedRoom.details.aiInsight}
                </p>
              </div>

              {/* Connected Devices Grid (Clickable) */}
              <h4 className="font-bold text-gray-900 mb-3 text-sm uppercase tracking-wider">Connected Devices</h4>
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                {selectedRoom.devices.map(device => {
                  const DeviceIcon = device.icon;
                  const devStatus = getStatusConfig(device.status);
                  return (
                    <div 
                      key={device.id} 
                      onClick={() => { setSelectedRoom(null); setSelectedDevice({ roomName: selectedRoom.name, ...device }); }}
                      className="border border-gray-200 rounded-xl p-3 flex items-center gap-3 cursor-pointer hover:border-red-300 hover:bg-red-50 transition-colors"
                    >
                      <div className={`p-2 rounded-lg ${devStatus.bg} ${devStatus.text}`}>
                        <DeviceIcon className="w-4 h-4" />
                      </div>
                      <div className="truncate">
                        <p className="font-bold text-sm text-gray-800 truncate">{device.name}</p>
                        <p className={`text-xs truncate ${devStatus.text}`}>{device.status}</p>
                      </div>
                    </div>
                  )
                })}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Device Details Modal */}
      {selectedDevice && (
        <div id="modal-overlay" onClick={closeModal} className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4 animate-in fade-in">
          <div className="bg-white rounded-3xl w-full max-w-lg overflow-hidden shadow-2xl animate-in zoom-in-95">
            {/* Modal Header */}
            <div className={`p-6 border-b ${getStatusConfig(selectedDevice.status).border} ${getStatusConfig(selectedDevice.status).bg} flex justify-between items-start`}>
              <div className="flex gap-4 items-center">
                <div className={`p-3 rounded-xl bg-white shadow-sm text-gray-700`}>
                  {(() => {
                    const DeviceIcon = selectedDevice.icon;
                    return <DeviceIcon className="w-8 h-8" />
                  })()}
                </div>
                <div>
                  <p className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">{selectedDevice.roomName}</p>
                  <h2 className="text-2xl font-extrabold text-gray-900 leading-none mb-2">{selectedDevice.name}</h2>
                  <div className={`inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-bold uppercase ${getStatusConfig(selectedDevice.status).badge}`}>
                    {selectedDevice.status}
                  </div>
                </div>
              </div>
              <button onClick={() => setSelectedDevice(null)} className="p-2 bg-white/50 rounded-full hover:bg-white transition-colors text-gray-500">
                <X className="w-5 h-5" />
              </button>
            </div>
            
            <div className="p-6">
              {/* Primary Metric */}
              <div className="text-center mb-6">
                <p className="text-sm text-gray-500 font-medium mb-1">Current Telemetry</p>
                <p className={`text-2xl font-extrabold ${getStatusConfig(selectedDevice.status).text}`}>
                  {selectedDevice.metric}
                </p>
              </div>

              {/* Hardware Specs Grid */}
              <div className="bg-gray-50 rounded-2xl border border-gray-100 p-4 mb-6">
                <h4 className="font-bold text-gray-800 text-sm mb-3">Hardware Information</h4>
                <div className="grid grid-cols-2 gap-y-3 text-sm">
                  <div>
                    <p className="text-gray-500 text-xs">Model</p>
                    <p className="font-semibold text-gray-900">{selectedDevice.details.model}</p>
                  </div>
                  <div>
                    <p className="text-gray-500 text-xs">Firmware</p>
                    <p className="font-semibold text-gray-900">{selectedDevice.details.firmware}</p>
                  </div>
                  <div>
                    <p className="text-gray-500 text-xs">Uptime</p>
                    <p className="font-semibold text-gray-900">{selectedDevice.details.uptime}</p>
                  </div>
                  <div>
                    <p className="text-gray-500 text-xs">Current Draw</p>
                    <p className="font-semibold text-gray-900">{selectedDevice.details.draw}</p>
                  </div>
                </div>
              </div>

              {/* AI Diagnostic */}
              <div className="bg-gradient-to-r from-gray-900 to-gray-800 rounded-2xl p-5 text-white relative overflow-hidden">
                <div className="absolute top-0 right-0 p-3 opacity-10">
                  <Zap className="w-16 h-16" />
                </div>
                <div className="relative z-10">
                  <div className="flex items-center gap-2 mb-2">
                    <Bot className="w-5 h-5 text-red-400" />
                    <h4 className="font-bold text-white text-sm">AI Diagnostic Log</h4>
                  </div>
                  <p className="text-gray-300 text-sm leading-relaxed mb-4">
                    {selectedDevice.details.aiInsight}
                  </p>
                  
                  {selectedDevice.details.aiSolution && selectedDevice.status !== 'optimal' && (
                    <div className="bg-white/10 border border-white/20 rounded-xl p-4 mt-2 mb-4">
                      <div className="flex items-center gap-2 mb-1.5">
                        <CheckCircle2 className="w-4 h-4 text-green-400" />
                        <h4 className="font-bold text-white text-sm">Suggested Solution</h4>
                      </div>
                      <p className="text-gray-200 text-sm">
                        {selectedDevice.details.aiSolution}
                      </p>
                    </div>
                  )}
                  
                  {selectedDevice.status !== 'optimal' && (
                    <button className="mt-4 w-full bg-red-600 hover:bg-red-700 text-white font-bold py-2 rounded-xl transition-colors text-sm">
                      Dispatch Technician
                    </button>
                  )}
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

export default Insights
